### ISSUE TITLE
Connectionless Presentation of Credentials Protocol

### ISSUE THREAD

**Issue by essbante-io** [hyperledger/identus#25]
Build the capability to allow for the presentation (or sharing) of digital credentials without a direct, ongoing connection between the presenter (the credential holder) and the verifier (the entity requesting to validate the credential). 

This means that individuals can prove their identity or qualifications in various situations without needing a DIDComm connection to the verifier, possibly through pre-verified or self-authenticating credentials.

- [x] hyperledger/identus-edge-agent-sdk-ts/pull/272
- [x] hyperledger/identus-edge-agent-sdk-swift/pull/171
- [x] hyperledger/identus-edge-agent-sdk-kmp/pull/192

**Comment by mixmix** [comment]
I'd love to see more info on these issues - links out to PRs / docs maybe

Actually I think this was released in SDK 6.1.0 right? Raises the question of how living this roadmap is

**Comment by elribonazo** [comment]
@mixmix Have updated the ticket description as we are moving to github projects. 
This card is completed so far, we can open new issues, etc but this is already completed.

We should discuss if we want to re-use oob links, I would propose to open an issue or a discussion in https://github.com/hyperledger/identus/discussions

**Comment by mineme0110** [comment]
https://github.com/hyperledger/identus-cloud-agent/issues/1426
