### ISSUE TITLE
Connectionless Issuance of Credentials Protocol

### ISSUE THREAD

**Issue by essbante-io** [hyperledger/identus#26]
Build the capability to allow for the issuance of digital credentials without the need for a persistent, direct connection between the issuer (the entity granting the credential) and the recipient (the individual or entity receiving the credential). It enables a more flexible and efficient way of issuing credentials, where recipients can receive their credentials through various channels without needing a live, continuous connection with the issuer.

- [ ] hyperledger/identus-edge-agent-sdk-ts/pull/305
- [ ] hyperledger/identus-edge-agent-sdk-ts/pull/304
- [ ] hyperledger/identus-edge-agent-sdk-ts/pull/294
- [ ] hyperledger/identus-edge-agent-sdk-ts/pull/293
- [ ] hyperledger/identus-edge-agent-sdk-kmp/pull/207
- [ ] hyperledger/identus-edge-agent-sdk-swift/pull/171
